apiVersion: apps/v1
kind: Deployment
metadata:
  name: segmentation-deployment
spec:
  selector:
    matchLabels:
      app: segmentation
  template:
    metadata:
      labels:
        app: segmentation
    spec:
      containers:
      - name: segmentation
        image: gcr.io/cedar-talent-279001/segmentation:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: segmentation
spec:
  type: ClusterIP
  selector:
    app: segmentation
  ports:
  - port: 8080
    targetPort: 8080
